apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-event-watcher-role-binder
subjects:
  - kind: ServiceAccount
    name: k8s-event-watcher-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-event-watcher-cluster-role
  apiGroup: rbac.authorization.k8s.io
